import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

/// Dart port of `@vaultkeep/crypto` — BYTE-COMPATIBLE with the node core, so
/// one vault decrypts on every platform:
///
///   key      = Argon2id(masterPassword, salt)
///   verifier = HMAC-SHA256(key, "vaultkeep-auth-verifier:" + password)
///   blob     = base64( nonce(12) ‖ ciphertext ‖ gcmTag(16) )
///
/// Compatibility is proven by test/crypto_compat_test.dart against vectors
/// generated by the node implementation. A wrong key or tampered blob makes
/// [decryptBlob] throw (GCM auth-tag verification) — never returns garbage.
class KdfParams {
  final int memoryKiB;
  final int iterations;
  final int parallelism;
  const KdfParams({
    required this.memoryKiB,
    required this.iterations,
    required this.parallelism,
  });

  /// Shared defaults — must equal the server/desktop/web defaults.
  static const defaults =
      KdfParams(memoryKiB: 65536, iterations: 3, parallelism: 4);

  Map<String, dynamic> toJson() => {
        'memoryKiB': memoryKiB,
        'iterations': iterations,
        'parallelism': parallelism,
      };
  factory KdfParams.fromJson(Map<String, dynamic> j) => KdfParams(
        memoryKiB: j['memoryKiB'] as int,
        iterations: j['iterations'] as int,
        parallelism: j['parallelism'] as int,
      );
}

const _nonceBytes = 12;

Future<Uint8List> deriveMasterKey(
  String masterPassword,
  String saltB64,
  KdfParams params,
) async {
  final argon2 = Argon2id(
    memory: params.memoryKiB,
    iterations: params.iterations < 1 ? 1 : params.iterations,
    parallelism: params.parallelism,
    hashLength: 32,
  );
  final key = await argon2.deriveKeyFromPassword(
    password: masterPassword,
    nonce: base64.decode(saltB64),
  );
  return Uint8List.fromList(await key.extractBytes());
}

/// Must match the node core's `deriveAuthVerifier` byte-for-byte.
Future<String> deriveAuthVerifier(Uint8List key, String masterPassword) async {
  final mac = await Hmac.sha256().calculateMac(
    utf8.encode('vaultkeep-auth-verifier:$masterPassword'),
    secretKey: SecretKey(key),
  );
  return base64.encode(mac.bytes);
}

Future<String> encryptBlob(Uint8List key, String plaintext) async {
  final aes = AesGcm.with256bits(nonceLength: _nonceBytes);
  final box = await aes.encrypt(
    utf8.encode(plaintext),
    secretKey: SecretKey(key),
  );
  final out = BytesBuilder()
    ..add(box.nonce)
    ..add(box.cipherText)
    ..add(box.mac.bytes);
  return base64.encode(out.toBytes());
}

/// Throws [SecretBoxAuthenticationError] on a wrong key or tampering.
Future<String> decryptBlob(Uint8List key, String blobB64) async {
  final blob = base64.decode(blobB64);
  if (blob.length < _nonceBytes + 16) {
    throw const FormatException('ciphertext too short / malformed');
  }
  final aes = AesGcm.with256bits(nonceLength: _nonceBytes);
  final plain = await aes.decrypt(
    SecretBox(
      blob.sublist(_nonceBytes, blob.length - 16),
      nonce: blob.sublist(0, _nonceBytes),
      mac: Mac(blob.sublist(blob.length - 16)),
    ),
    secretKey: SecretKey(key),
  );
  return utf8.decode(plain);
}

/// Wipe key material when locking.
void zeroKey(Uint8List key) => key.fillRange(0, key.length, 0);
