import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:vaultkeep_mobile/core/vault_crypto.dart';

/// Byte-compatibility with `@vaultkeep/crypto` (node), proven against
/// fixtures generated by the node implementation itself
/// (test/fixtures/crypto_vectors.json). Same password + salt + params must
/// yield the same key; node-encrypted blobs must decrypt here and vice versa
/// (round-trip), and the auth verifier must match exactly.
void main() {
  final vectors = jsonDecode(
    File('test/fixtures/crypto_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  group('Argon2id key derivation matches the node core', () {
    for (final (i, v) in (vectors['kdf'] as List<dynamic>).indexed) {
      test('vector $i (parallelism ${(v['params'] as Map)['parallelism']})',
          () async {
        final params =
            KdfParams.fromJson((v['params'] as Map).cast<String, dynamic>());
        final key = await deriveMasterKey(
            v['password'] as String, v['saltB64'] as String, params);
        expect(base64.encode(key), v['keyB64']);
      });
    }
  });

  test('auth verifier matches the node core byte-for-byte', () async {
    final v = vectors['verifier'] as Map<String, dynamic>;
    final key = Uint8List.fromList(base64.decode(v['keyB64'] as String));
    expect(await deriveAuthVerifier(key, v['password'] as String), v['expected']);
  });

  group('AES-256-GCM blobs interoperate with the node core', () {
    for (final (i, b) in (vectors['blobs'] as List<dynamic>).indexed) {
      test('decrypts node-encrypted blob $i', () async {
        final key = Uint8List.fromList(base64.decode(b['keyB64'] as String));
        expect(await decryptBlob(key, b['blobB64'] as String), b['plaintext']);
      });
    }

    test('round-trips locally with a fresh nonce each time', () async {
      final key = Uint8List.fromList(List.generate(32, (i) => i));
      final a = await encryptBlob(key, 'secret payload');
      final b = await encryptBlob(key, 'secret payload');
      expect(a, isNot(b)); // fresh random nonce
      expect(await decryptBlob(key, a), 'secret payload');
      expect(await decryptBlob(key, b), 'secret payload');
    });

    test('a wrong key is rejected via the GCM auth tag', () async {
      final key = Uint8List.fromList(List.generate(32, (i) => i));
      final wrong = Uint8List.fromList(List.generate(32, (i) => i + 1));
      final blob = await encryptBlob(key, 'secret');
      expect(() => decryptBlob(wrong, blob),
          throwsA(isA<SecretBoxAuthenticationError>()));
    });

    test('tampered ciphertext is rejected', () async {
      final key = Uint8List.fromList(List.generate(32, (i) => i));
      final blob = base64.decode(await encryptBlob(key, 'secret'));
      blob[14] ^= 0xff;
      expect(() => decryptBlob(key, base64.encode(blob)),
          throwsA(isA<SecretBoxAuthenticationError>()));
    });
  });
}
