import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:vaultkeep_mobile/core/devicekeys.dart';

/// Byte-compatibility with `@vaultkeep/crypto`'s devicekeys.ts (node), proven
/// against fixtures generated by the node implementation itself
/// (test/fixtures/device_recovery_vectors.json) — the actual server verifies
/// device-approval signatures using Node's SPKI/PKCS8 DER import, so a
/// mobile-issued key MUST decode to the exact same raw bytes and produce
/// byte-identical (deterministic) EdDSA signatures.
void main() {
  final vectors = jsonDecode(
    File('test/fixtures/device_recovery_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  group('Ed25519 signing keys', () {
    test('a locally-generated keypair round-trips through sign/verify',
        () async {
      final pair = await generateSigningKeys();
      const message = 'approve-device:some-id';
      final sig = await signMessage(pair.privateKey, message);
      expect(await verifyMessage(pair.publicKey, message, sig), true);
    });

    test('node-generated signature verifies against the node public key',
        () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      expect(
        await verifyMessage(
            s['publicKeyDer'] as String, s['message'] as String, s['signature'] as String),
        true,
      );
    });

    test('signing the node fixture message with the node private key '
        'reproduces the EXACT node signature (EdDSA is deterministic)',
        () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      final sig =
          await signMessage(s['privateKeyDer'] as String, s['message'] as String);
      expect(sig, s['signature']);
    });

    test('a signature from a different keypair is rejected', () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      final other = vectors['signingOther'] as Map<String, dynamic>;
      expect(
        await verifyMessage(other['publicKeyDer'] as String,
            s['message'] as String, s['signature'] as String),
        false,
      );
    });

    test('a tampered message is rejected', () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      expect(
        await verifyMessage(s['publicKeyDer'] as String,
            '${s['message']}-tampered', s['signature'] as String),
        false,
      );
    });

    test('malformed key material fails closed (never throws past the caller)',
        () async {
      expect(await verifyMessage('not-valid-base64-der', 'msg', 'sig'), false);
    });
  });

  group('DER wrapping matches the node core exactly', () {
    test('a generated Ed25519 public key strips to the same raw length as node',
        () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      final der = base64.decode(s['publicKeyDer'] as String);
      final raw = base64.decode(s['publicKeyRaw'] as String);
      expect(der.length, 44);
      expect(raw.length, 32);
      expect(der.sublist(der.length - 32), raw);
    });

    test('a generated Ed25519 private key strips to the same raw seed as node',
        () async {
      final s = vectors['signing'] as Map<String, dynamic>;
      final der = base64.decode(s['privateKeyDer'] as String);
      final raw = base64.decode(s['privateKeyRaw'] as String);
      expect(der.length, 48);
      expect(der.sublist(der.length - 32), raw);
    });

    test('X25519 DER lengths match node (44 / 48 bytes)', () async {
      final x = vectors['exchange'] as Map<String, dynamic>;
      expect(base64.decode(x['alicePublicKeyDer'] as String).length, 44);
      expect(base64.decode(x['alicePrivateKeyDer'] as String).length, 48);
    });
  });

  group('X25519 ECDH', () {
    test('a fresh keypair derives the same secret both directions', () async {
      final a = await generateExchangeKeys();
      final b = await generateExchangeKeys();
      final fromA = await deriveSharedSecret(a.privateKey, b.publicKey);
      final fromB = await deriveSharedSecret(b.privateKey, a.publicKey);
      expect(fromA, fromB);
    });

    test('reproduces the exact node-derived shared secret', () async {
      final x = vectors['exchange'] as Map<String, dynamic>;
      final fromAlice = await deriveSharedSecret(
          x['alicePrivateKeyDer'] as String, x['bobPublicKeyDer'] as String);
      final fromBob = await deriveSharedSecret(
          x['bobPrivateKeyDer'] as String, x['alicePublicKeyDer'] as String);
      final expected = base64.decode(x['sharedSecret'] as String);
      expect(fromAlice, expected);
      expect(fromBob, expected);
    });
  });
}
