import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:vaultkeep_mobile/core/devicekeys.dart' as devicekeys;
import 'package:vaultkeep_mobile/core/recovery.dart';

/// Byte-compatibility with `@vaultkeep/crypto`'s recovery.ts (node), proven
/// against fixtures generated by the node implementation itself
/// (test/fixtures/device_recovery_vectors.json) — recovery only works if a
/// wrapped blob made by ANY client decrypts on any other, since the account
/// owner and their emergency contact are rarely on the same platform.
void main() {
  final vectors = jsonDecode(
    File('test/fixtures/device_recovery_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  group('recovery key format', () {
    test('generateRecoveryKey produces the VK-xxxxx-... shape', () {
      final key = generateRecoveryKey();
      expect(key, matches(RegExp(r'^VK(-[0-9A-Z]{5}){5}$')));
      // Crockford base32 excludes I, L, O, U.
      expect(key, isNot(contains(RegExp(r'[ILOU]'))));
    });

    test('two generated keys are (essentially certainly) different', () {
      expect(generateRecoveryKey(), isNot(generateRecoveryKey()));
    });

    test('normalizeRecoveryKey matches the node core', () {
      final v = vectors['recovery'] as Map<String, dynamic>;
      expect(normalizeRecoveryKey(v['recoveryKey'] as String), v['normalized']);
    });

    test('normalization is forgiving of case, separators, and misreadings',
        () {
      final v = vectors['recoveryMessyInput'] as Map<String, dynamic>;
      final expected = (vectors['recovery'] as Map<String, dynamic>)['normalized'];
      expect(normalizeRecoveryKey(v['messy'] as String), expected);
    });
  });

  group('HKDF split matches the node core exactly', () {
    test('authVerifier and wrapKey reproduce the node fixture', () async {
      final v = vectors['recovery'] as Map<String, dynamic>;
      final parts = await deriveRecoveryParts(
          v['recoveryKey'] as String, v['saltB64'] as String);
      expect(parts.authVerifier, v['authVerifier']);
      expect(base64.encode(parts.wrapKey), v['wrapKeyB64']);
    });

    test('a messily-typed recovery key derives the SAME parts', () async {
      final messy = vectors['recoveryMessyInput'] as Map<String, dynamic>;
      final salt = (vectors['recovery'] as Map<String, dynamic>)['saltB64'] as String;
      final parts = await deriveRecoveryParts(messy['messy'] as String, salt);
      expect(parts.authVerifier, messy['expectAuthVerifier']);
      expect(base64.encode(parts.wrapKey), messy['expectWrapKeyB64']);
    });

    test('a different recovery key derives different, unrelated parts',
        () async {
      final v = vectors['recovery'] as Map<String, dynamic>;
      final other = await deriveRecoveryParts(
          generateRecoveryKey(), v['saltB64'] as String);
      expect(other.authVerifier, isNot(v['authVerifier']));
    });
  });

  group('wrap/unwrap master key', () {
    test('unwraps a node-produced wrapped blob to the exact master key',
        () async {
      final v = vectors['recovery'] as Map<String, dynamic>;
      final wrapKey = Uint8List.fromList(base64.decode(v['wrapKeyB64'] as String));
      final key = await unwrapMasterKey(wrapKey, v['wrappedBlob'] as String);
      expect(base64.encode(key), v['masterKeyB64']);
    });

    test('round-trips locally', () async {
      final wrapKey = Uint8List.fromList(List.generate(32, (i) => i));
      final masterKey = Uint8List.fromList(List.generate(32, (i) => 31 - i));
      final blob = await wrapMasterKey(wrapKey, masterKey);
      expect(await unwrapMasterKey(wrapKey, blob), masterKey);
    });

    test('the wrong recovery key fails to unwrap (GCM auth tag)', () async {
      final v = vectors['recovery'] as Map<String, dynamic>;
      final wrongParts =
          await deriveRecoveryParts(generateRecoveryKey(), v['saltB64'] as String);
      expect(
        () => unwrapMasterKey(wrongParts.wrapKey, v['wrappedBlob'] as String),
        throwsA(anything),
      );
    });
  });

  group('emergency contact sealing', () {
    test('unseals a node-sealed blob to the exact master key', () async {
      final v = vectors['emergencyContact'] as Map<String, dynamic>;
      final wrapped = ContactWrappedKey(
          v['ephemeralPublicKeyDer'] as String, v['blob'] as String);
      final key = await unwrapKeyFromContact(
          v['contactPrivateKeyDer'] as String, wrapped);
      expect(base64.encode(key), v['masterKeyB64']);
    });

    test('a fresh seal/unseal round-trips locally', () async {
      final masterKey = Uint8List.fromList(List.generate(32, (i) => i));
      final keys = await devicekeys.generateExchangeKeys();
      final sealed = await wrapKeyForContact(masterKey, keys.publicKey);
      final unsealed = await unwrapKeyFromContact(keys.privateKey, sealed);
      expect(unsealed, masterKey);
    });

    test('the wrong contact cannot unseal the blob', () async {
      final v = vectors['emergencyContact'] as Map<String, dynamic>;
      final wrapped = ContactWrappedKey(
          v['ephemeralPublicKeyDer'] as String, v['blob'] as String);
      final someoneElse = await devicekeys.generateExchangeKeys();
      expect(
        () => unwrapKeyFromContact(someoneElse.privateKey, wrapped),
        throwsA(anything),
      );
    });
  });
}
